services:
  forgejo_runner:
    image: code.forgejo.org/forgejo/runner:7.0.0
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    volumes:
      #- ./data/config.yaml:/config.yaml # 可选配置
      - ./data/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      #- CONFIG_FILE=/config.yaml
      - FORGEJO_INSTANCE_URL=${FORGEJO_INSTANCE_URL}
      - FORGEJO_RUNNER_REGISTRATION_TOKEN=${RUNNER_REGISTRATION_TOKEN}
      - FORGEJO_RUNNER_NAME=${RUNNER_NAME}
      - FORGEJO_RUNNER_LABELS=${RUNNER_LABELS}
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:
    external: true
