version: "3.9"

services:
  forgejo_runner:
    image: code.forgejo.org/forgejo/runner:7.0.0
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    command: >-
      bash -c '
        if [ ! -f /data/.runner ]; then
          forgejo-runner create-runner-file --connect \
            --instance ${FORGEJO_INSTANCE_URL} \
            --name ${RUNNER_NAME} \
            --secret ${RUNNER_SHARED_SECRET} ;
          sed -i -e "s|\"labels\": null|\"labels\": [\"${RUNNER_LABELS}\"]|" /data/.runner ;
          forgejo-runner generate-config --config /data/config.yml ;
          sed -i -e "s|  level: info|  level: debug|" /data/config.yml ;
        fi ;
        forgejo-runner --config /data/config.yml daemon
      '
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FORGEJO_INSTANCE_URL=${FORGEJO_INSTANCE_URL}
      - RUNNER_NAME=${RUNNER_NAME}
      - RUNNER_LABELS=${RUNNER_LABELS}
      - RUNNER_SHARED_SECRET=${RUNNER_SHARED_SECRET}
    labels:  
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
