services:
  tinyauth:
    image: ghcr.io/steveiliop56/tinyauth:v5.0.1
    container_name: ${CONTAINER_NAME}
    environment:
      # ---- 通用配置 ----
      - TINYAUTH_APPURL=${PANEL_TINYAUTH_APP_URL}
      - TINYAUTH_SECRET=${PANEL_TINYAUTH_SECRET}
      - TINYAUTH_AUTH_SESSIONEXPIRY=${PANEL_TINYAUTH_SESSION_EXPIRY}
      - TINYAUTH_UI_TITLE=${PANEL_TINYAUTH_APP_TITLE}
      - TINYAUTH_OAUTH_AUTOREDIRECT=${PANEL_TINYAUTH_OAUTH_AUTO_REDIRECT}
      - TINYAUTH_UI_BACKGROUNDIMAGE=${PANEL_TINYAUTH_BACKGROUND_IMAGE}

      # ---- Generic (示例 Linux.Do) ----
      - TINYAUTH_OAUTH_PROVIDERS_PLACEHOLDER_CLIENTID=${PANEL_TINYAUTH_GENERIC_CLIENT_ID}
      - TINYAUTH_OAUTH_PROVIDERS_PLACEHOLDER_CLIENTSECRET=${PANEL_TINYAUTH_GENERIC_CLIENT_SECRET}
      - TINYAUTH_OAUTH_PROVIDERS_PLACEHOLDER_NAME=${PANEL_TINYAUTH_GENERIC_NAME}
      - TINYAUTH_OAUTH_PROVIDERS_PLACEHOLDER_AUTHURL=${PANEL_TINYAUTH_GENERIC_AUTH_URL}
      - TINYAUTH_OAUTH_PROVIDERS_PLACEHOLDER_TOKENURL=${PANEL_TINYAUTH_GENERIC_TOKEN_URL}
      - TINYAUTH_OAUTH_PROVIDERS_PLACEHOLDER_USERINFOURL=${PANEL_TINYAUTH_GENERIC_USER_INFO_URL}
      - TINYAUTH_OAUTH_PROVIDERS_PLACEHOLDER_REDIRECTURL=${PANEL_TINYAUTH_APP_URL}/api/oauth/callback/${PANEL_TINYAUTH_PROVIDER_ID}
      - TINYAUTH_OAUTH_PROVIDERS_PLACEHOLDER_SCOPES=${PANEL_TINYAUTH_GENERIC_SCOPES}

    ports:
      - "${PANEL_APP_PORT_HTTP}:3000"
    labels:
      createdBy: "Apps"
    networks:
      - 1panel-network
    restart: always
    volumes:
      - ./data:/data

networks:
  1panel-network:
    external: true
