name: Sync commits to CNB (force)

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:
    inputs:
      reason:
        description: 'Manual trigger reason'
        required: false
        default: 'Manual run'

jobs:
  sync:
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v5
        with:
          ref: main

      - name: Add CNB remote and force push
        env:
          CNB_USERNAME: ${{ secrets.CNB_USERNAME }}
          CNB_TOKEN: ${{ secrets.CNB_TOKEN }}
        run: |
          rm -rf .git
          git init
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          git commit -m "${{ github.event.head_commit.message }}==>[$(date +"%Y-%m-%d %H:%M:%S")]"
          git branch -M main
          git remote add origin "https://${{ secrets.CNB_USERNAME }}:${{ secrets.CNB_TOKEN }}@cnb.cool/liiiu/appstore.git"
          git push --force --quiet origin main
