name: Sync commits to CNB (force)

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "${{ secrets.CNB_USERNAME }}"
          git config --global user.email "${{ secrets.CNB_USERNAME }}@users.noreply.github.com"

      - name: Add CNB remote and force push
        env:
          CNB_USERNAME: ${{ secrets.CNB_USERNAME }}
          CNB_TOKEN: ${{ secrets.CNB_TOKEN }}
        run: |
          git remote remove cnb || true
          git remote add cnb "https://${CNB_USERNAME}:${CNB_TOKEN}@cnb.cool/Liiiu/Blog.git"
          git push cnb main --force
